language: python
python:
- '2.7'
- '3.2'
install:
- pip install -r requirements/test.txt
script: nosetests
deploy:
  provider: pypi
  user: davydany
  password:
    secure: qmq/l+jWE1bcVLsSE52O1fgINLa3nknYkrnLTTNzYfZ/HMq448qBC4heDlSaWcEpbDUhMKg4DNf1CJ+3F1t4xKIuVGE3nyKTYLdrcc9uCeFtoznjK7ajPG5S1/uPKhQW9p9GzoxAcInj8mDjyT+zB3y69Re2mgcLBHxO5/VBZs9mfoKmZCWgt0DV0pxgjg8yzTZmGIjVVJhmw4rrliX2Vzg0bj074Vgv99ZJqHhPWhdozsl8J4ufxfP4XSC7Sc6E6tuYlHKbqXQWk6R1UYAtRToNO5KRs+UjUSpCvICF5xtntl4oraYEPmGp1sCsAKt3liZZ5zZFgHvvkNMC4zjSMKg8q0zS6i2zpYJhtXly5PdEbCbcabOLVgX6bZGGDck5YGUmFZp3UcQs6H0wSInexsznIInxtmi6xWeSEg4eIl6rL3nsmyURg6IafLBr46vLxQXP5Hfn58XATPQedVQBr8iP9rY1ZkutYJaPu1PWrLa1UO+S9vpGp/BFiUH/pnVSQSXx8g2Gk2/20Ijlzo0IJtbiLOWdYJ8dBUxy+8lJv5MpenU+OkvPIFZlNMraAhXche7ZRjA6jt75fqYrHsnmbLP8RK/9MyrnX8NXKVUEeyYwwI5jZRHMm1MXTExDOVybyx0VBhB0HojUj0sdmacVV4biUlz+EJCt0u/xbtr+syE=
  on:
    distributions: sdist bdist_wheel
    repo: aeroxis/sultan
